CREATE TABLE  `users` (
`id` INT NOT NULL AUTO_INCREMENT,
`uname` VARCHAR( 64 ) NOT NULL ,
`password` VARCHAR( 256 ) NOT NULL,

PRIMARY KEY (id),
INDEX (uname)
) ENGINE = INNODB;

CREATE TABLE  `tokens` (
`id` INT NOT NULL AUTO_INCREMENT ,
`token` VARCHAR( 256 ) NOT NULL ,
`user` VARCHAR( 64 ) NOT NULL ,
`created_at` TIMESTAMP NOT NULL ,
`expired_at` TIMESTAMP NOT NULL ,
PRIMARY KEY ( `id`),
INDEX (token)

) ENGINE = INNODB;